version: '2'
services:
  scan:
    build: .
    command: "python main.py --scan"
    restart: always
    volumes:
      - .:/opt/
  port:
    build: .
    command: "python main.py --port"
    restart: always
    volumes:
      - .:/opt/
  services:
    build: .
    command: "python main.py --services"
    restart: always
    volumes:
      - .:/opt/